Repository 0x192/universal-android-debloater, pull requests merged in 2022-11, with the labels that each got.

#359 Added some oppo/realme COS/RUI apps
  resources/assets/uad_lists.json
Labels: package::addition

#301 [Pkg] Add OnePlus packages
  resources/assets/uad_lists.json
Labels: package::addition

#294 [Pkg] More Samsung preinstalled junk
  resources/assets/uad_lists.json
Labels: package::addition

#247 [Pkg] Add OnePlus-specific packages
  resources/assets/uad_lists.json
Labels: package::addition

#363 Add Manufacturers names in debloat lists
  README.md
Labels: package::addition

#350 [Pkg] Add `com.tblenovo.center`
  resources/assets/uad_lists.json
Labels: package::addition

#307 [Pkg] Add Vivo/iQOO-specific packages
  README.md
  resources/assets/uad_lists.json
Labels: package::addition

#447 feat: backup/restore the state of a device
  CHANGELOG.md
  src/core/config.rs
  src/core/mod.rs
  src/core/save.rs
  src/core/sync.rs
  src/core/uad_lists.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/style.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
  src/gui/widgets/navigation_menu.rs
Labels: feature

#448 fix: UAD crash when interacting with work profiles
  src/core/sync.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
Labels: bug, crash, fix
