Repository 0x192/universal-android-debloater, pull requests merged in 2022-09, with the labels that each got.

#369 refactor: major code overhaul + support for the new Iced theme API
  Cargo.lock
  Cargo.toml
  src/core/sync.rs
  src/core/theme.rs
  src/core/uad_lists.rs
  src/core/utils.rs
  src/gui/mod.rs
  src/gui/style.rs
  src/gui/views/about.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
  src/gui/widgets/mod.rs
  src/gui/widgets/navigation_menu.rs
  src/gui/widgets/package_row.rs
Labels: build, refactor

#164 Add new Oppo bloatware
  resources/assets/uad_lists.json
Labels: package::addition

#374 feat: device-specific persistent configuration
  CHANGELOG.md
  src/core/config.rs
  src/core/sync.rs
  src/gui/mod.rs
  src/gui/style.rs
  src/gui/views/list.rs
  src/gui/views/settings.rs
  src/gui/widgets/package_row.rs
  src/main.rs
Labels: feature
